{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "embedded-koin-core-viewmodel",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.core",
          "module": "core-bundle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-koin-core-viewmodel-metadata-4.0.4.jar",
          "url": "embedded-koin-core-viewmodel-4.0.4.jar",
          "size": 9435,
          "sha512": "67f7bbc726a224e6cc2359edfed8723e41587667ce6675dfb7609495c674bb0856b71f89322581d4ee697750f3454f403dc07646a2177f81d95d7ac49b5ab9d9",
          "sha256": "cd22f01ff0a0c743f21fea1cd86f2b7e0c312bdcfdc5571f6bacea0412881137",
          "sha1": "cd40ec5fa4372790add5c677b65e57568f4c248e",
          "md5": "e1720330fd0ac56bcf167b50b2061b70"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "embedded-koin-core-viewmodel-kotlin-4.0.4-sources.jar",
          "url": "embedded-koin-core-viewmodel-4.0.4-sources.jar",
          "size": 10402,
          "sha512": "c5d997e9c84b82a44fc502d8b741402790d5af8a8cb553bc5042a739e9e202b363012d003defe981be59f9e26c8c04f19410106d5b8e4e174a2da1cbcb60f92c",
          "sha256": "947100ec5271b61fd15bdc3d40b702052b3cf8408994fd50f6c46ba00bbf4039",
          "sha1": "3a7ac122fbf3f40b58c4f2ecc3996de3659c6d79",
          "md5": "a0cfc2f7862a671b2ba31f4ac26f9576"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosarm64/4.0.4/embedded-koin-core-viewmodel-iosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosarm64/4.0.4/embedded-koin-core-viewmodel-iosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosarm64/4.0.4/embedded-koin-core-viewmodel-iosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iossimulatorarm64/4.0.4/embedded-koin-core-viewmodel-iossimulatorarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iossimulatorarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iossimulatorarm64/4.0.4/embedded-koin-core-viewmodel-iossimulatorarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iossimulatorarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iossimulatorarm64/4.0.4/embedded-koin-core-viewmodel-iossimulatorarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iossimulatorarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosx64/4.0.4/embedded-koin-core-viewmodel-iosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosx64/4.0.4/embedded-koin-core-viewmodel-iosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-iosx64/4.0.4/embedded-koin-core-viewmodel-iosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-iosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-js/4.0.4/embedded-koin-core-viewmodel-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-js",
        "version": "4.0.4"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-js/4.0.4/embedded-koin-core-viewmodel-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-js",
        "version": "4.0.4"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-js/4.0.4/embedded-koin-core-viewmodel-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-js",
        "version": "4.0.4"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-jvm/4.0.4/embedded-koin-core-viewmodel-jvm-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-jvm",
        "version": "4.0.4"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-jvm/4.0.4/embedded-koin-core-viewmodel-jvm-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-jvm",
        "version": "4.0.4"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-jvm/4.0.4/embedded-koin-core-viewmodel-jvm-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-jvm",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosarm64/4.0.4/embedded-koin-core-viewmodel-macosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosarm64/4.0.4/embedded-koin-core-viewmodel-macosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosarm64/4.0.4/embedded-koin-core-viewmodel-macosarm64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosarm64",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosx64/4.0.4/embedded-koin-core-viewmodel-macosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosx64/4.0.4/embedded-koin-core-viewmodel-macosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-macosx64/4.0.4/embedded-koin-core-viewmodel-macosx64-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-macosx64",
        "version": "4.0.4"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-wasm-js/4.0.4/embedded-koin-core-viewmodel-wasm-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-wasm-js",
        "version": "4.0.4"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-wasm-js/4.0.4/embedded-koin-core-viewmodel-wasm-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-wasm-js",
        "version": "4.0.4"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../embedded-koin-core-viewmodel-wasm-js/4.0.4/embedded-koin-core-viewmodel-wasm-js-4.0.4.module",
        "group": "io.insert-koin",
        "module": "embedded-koin-core-viewmodel-wasm-js",
        "version": "4.0.4"
      }
    }
  ]
}
