{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "embedded-koin-android",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core-viewmodel",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-koin-android-4.0.4.aar",
          "url": "embedded-koin-android-4.0.4.aar",
          "size": 279626,
          "sha512": "62bf9890e19c2e13a18617f3181dbc7607543ce94204b4eafe30dfcd80ea5f4ce55a69f8ae6f9c5b6568713ec77ca0dad7c4747c9044342d9a2843e8bc7b80f2",
          "sha256": "3a09d900a9e42ccc6b4deff67a9f2040ce2064a467671d35a3bf00d3db9f217a",
          "sha1": "0d4a78700872d9c7f9a7aae138ad63ff6ccaf961",
          "md5": "e6903f31efe1029640e21375903f347b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core-viewmodel",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.8.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-koin-android-4.0.4.aar",
          "url": "embedded-koin-android-4.0.4.aar",
          "size": 279626,
          "sha512": "62bf9890e19c2e13a18617f3181dbc7607543ce94204b4eafe30dfcd80ea5f4ce55a69f8ae6f9c5b6568713ec77ca0dad7c4747c9044342d9a2843e8bc7b80f2",
          "sha256": "3a09d900a9e42ccc6b4deff67a9f2040ce2064a467671d35a3bf00d3db9f217a",
          "sha1": "0d4a78700872d9c7f9a7aae138ad63ff6ccaf961",
          "md5": "e6903f31efe1029640e21375903f347b"
        }
      ]
    }
  ]
}
