{
  "formatVersion": "1.1",
  "component": {
    "url": "../../embedded-koin-core-viewmodel/4.0.4/embedded-koin-core-viewmodel-4.0.4.module",
    "group": "io.insert-koin",
    "module": "embedded-koin-core-viewmodel",
    "version": "4.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.core",
          "module": "core-bundle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-koin-core-viewmodel-jvm-4.0.4.jar",
          "url": "embedded-koin-core-viewmodel-jvm-4.0.4.jar",
          "size": 124286,
          "sha512": "742777ead9274cad136df214b4b82bc39720871f10aed19cc108a81ced7fed7de0b97d214deed7b8749d24b81874036db7f898959a720113851f893cb8dd039e",
          "sha256": "1f5f9ff37e2a97d039b95f8307a72dadefea11c2cf342b87950385097f0d674d",
          "sha1": "07420829e092593686d8a078f3fc6aa50a1232a4",
          "md5": "25eade5e8139b69449ca7eb1c1db02a0"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "embedded-koin-core",
          "version": {
            "requires": "4.0.4"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.8.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.core",
          "module": "core-bundle",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "embedded-koin-core-viewmodel-jvm-4.0.4.jar",
          "url": "embedded-koin-core-viewmodel-jvm-4.0.4.jar",
          "size": 124286,
          "sha512": "742777ead9274cad136df214b4b82bc39720871f10aed19cc108a81ced7fed7de0b97d214deed7b8749d24b81874036db7f898959a720113851f893cb8dd039e",
          "sha256": "1f5f9ff37e2a97d039b95f8307a72dadefea11c2cf342b87950385097f0d674d",
          "sha1": "07420829e092593686d8a078f3fc6aa50a1232a4",
          "md5": "25eade5e8139b69449ca7eb1c1db02a0"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "embedded-koin-core-viewmodel-jvm-4.0.4-sources.jar",
          "url": "embedded-koin-core-viewmodel-jvm-4.0.4-sources.jar",
          "size": 10402,
          "sha512": "c5d997e9c84b82a44fc502d8b741402790d5af8a8cb553bc5042a739e9e202b363012d003defe981be59f9e26c8c04f19410106d5b8e4e174a2da1cbcb60f92c",
          "sha256": "947100ec5271b61fd15bdc3d40b702052b3cf8408994fd50f6c46ba00bbf4039",
          "sha1": "3a7ac122fbf3f40b58c4f2ecc3996de3659c6d79",
          "md5": "a0cfc2f7862a671b2ba31f4ac26f9576"
        }
      ]
    }
  ]
}
