pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
        // Repositório local para o SDK Auttar
        maven {
            url = uri("repository")
        }
    }
}

rootProject.name = "AuttarV3Integration"
include ':app'
